### ISSUE TITLE
string to float exception

### ISSUE THREAD

**Issue by saimn** [coleifer/sqlite-browser#2]
Hi,
when trying to view the content of a table, I get an exception : 
```
ValueError: could not convert string to float:
```
Full traceback here: https://gist.github.com/saimn/7471a06f96be0d6a285b
The value is an empty string, and peewee tries to convert it to a float value.

Maybe the issue comes from the database I'm visualizing, but would it be possible to catch this exception in sqlite-browser and ignore this specific value ?
From the traceback I guess it is not so easy to do in sqlite-browser, maybe in peewee ?
Otherwise sqlite-browser is a nice and useful tool, thanks for that !

**Comment by coleifer** [comment]
Hmm, peewee tries to infer types if no type info is available. Sqlite doesn't enforce types, though, so I can see how this might come up. I'll look into a fix.

**Comment by coleifer** [comment]
Unfortunately there doesn't seem to be an easy fix coming to mind... Peewee infers type information based on the schema, and based on those types it will attempt to coerce values coming off the cursor to the appropriate python type. If a problem occurs coercing a value, peewee throws the exception you see.

Perhaps you could try cleaning up your data, meanwhile I can write a more helpful message.

something like,

```sql
update my_table set float_column = NULL where float_column = '';
```

**Comment by saimn** [comment]
Ok, thanks for having looked at this.
