### ISSUE TITLE
Permalinks for queries

### ISSUE THREAD

**Issue by rbagd** [coleifer/sqlite-browser#4]
I was wondering whether it'd be possible to add permanent links for query pages. It's useful for bookmarking or fast sharing of links without having to re-enter again the specific query. I'd expect something along the lines:

* http://localhost/my_table/query/.WHERE?cond1=AAA&cond2=TRUE.ORDERBY?column1

I guess that at least simple keywords such `WHERE`, `LIMIT`, `ORDER BY` and `GROUP BY` would be sufficient. Covering all cases isn't necessary for a simple lightweight tool.

Thanks for this sweet tool by the way.

**Comment by coleifer** [comment]
Ah, interesting idea. I can look into this for sure.

**Comment by coleifer** [comment]
To implement the clause-specific stuff, I'd have to parse the actual SQL which I'm not thinking I will end up implementing, but maybe there's an easy way to encode the whole query.
